#!/usr/bin/env bash
# Configure Nginx server to redirect to another page.
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo sed -i '29 i \ rewrite ^\/$ http:\/\/www.77holsch.tech\/redirect_me permanent;' /etc/nginx/sites-available/default
sudo service nginx start
