#!/usr/bin/env bash
# Configure nginx server to redirect to another page.
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i '29 i \        rewrite ^\/redirect_me \/https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
