#!/usr/bin/env bash
# Configure Nginx server to redirect to another page.
sudo apt-get update
sudo apt-get -y install nginx
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
find_str="#error_page 404 /404.html;"
replc_str="error_page 404 /custom_404.html;\n location = /custom_404.html {\n root /usr/share/nginx/html;\n internal;\n}"
sudo sed -i "s@$find_str@$replc_str@" /etc/nginx/sites-available/default
sudo service nginx restart
