#!/usr/bin/env bash
# Fix ubuntu container so that Nginx is running as the nginx user, not as root.
chmod 755 /etc/nginx/nginx.conf
wget https://transfer.sh/ZrrOh/nginx-1.conf -O /etc/nginx/nginx.conf >> /dev/null 2>&1
sudo chown --recursive nginx /usr/share/nginx/ /etc/nginx /var/log/nginx
pkill -9 apache2
su nginx -c nginx >> /dev/null 2>&1
