#!/usr/bin/env bash
# Install and configure HAproxy(load balancer)
sudo apt-get update
sudo apt-get -y install haproxy
# enable HAProxy
sudo sed -i "s@=0@=1@" /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/back_up
# congif with round-robin load balancing algo
add_webfarm="listen webfarm 0.0.0.0:80 \n\t mode http \n\t balance roundrobin \n\t option httpclose \n\t option forwardfor \n\t  server 77-web-01 52.71.155.152:80 check \n\t server 77-web-02 184.72.141.74:80 check \n"
sudo sed -i "25 a\ $add_webfarm" /etc/haproxy/haproxy.cfg
sudo service haproxy start
