#!/usr/bin/env bash
# This script displays FizzBuzz test.
for ((i=1;i<=100;i+=1)); do
    if ((i % 15 == 0)) ; then
       echo "FizzBuzz"
    elif ((i % 5 == 0)); then
       echo "Buzz"
    elif ((i % 3 == 0)); then
       echo "Fizz"
    else
       echo "$i"
    fi
done
