#!/usr/bin/env bash
# This script displays Holberton School 10 times, but for the 9th iteration, also displays Hi.
i=1
while [ $i -le 10 ]; do
    echo "Holberton School"
    if [ "$i" == "9" ]; then
	echo "Hi"
    fi
    let i+=1
done
