#!/usr/bin/env bash
# this script configures a Ubuntu server to change localhost ip and fb ip
cp /etc/hosts ~/hosts.new
sed -i "/localhost/s/.1/.2/" ~/hosts.new
chng_fb="\n # changing facebooks ip \n 8.8.8.8 \t facebook.com\n"
sed -i "7 a\ $chng_fb" ~/hosts.new
cp -f ~/hosts.new /etc/hosts