#!/usr/bin/env bash
# debug Nginx in an ubuntu container's to find which port its listening on and make it listen on 80
service nginx stop
cp /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
