#!/usr/bin/env bash
# This script displays Holberton School 10 times, but for the 9th iteration, also displays Hi.
i=0
while [ $i -lt 10 ]; do
    echo "Holberton School"
    if [ "$i" == "8" ]; then
	echo "Hi"
    fi
    let i+=1
done
