#!/usr/bin/env bash
# This script displays Holberton School 10 times, but at 4th iteration displays bad luck and at 8th good luck.
i=1
while [ $i -le 10 ]; do
    if [ "$i" == "4" ]; then
	echo "bad luck"
    elif [ "$i" == "8" ]; then
	echo "good luck"
    else
	echo "Holberton School"
    fi
    let i+=1
done
